# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag] ## , jekyll-multiple-languages-plugin]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Apartmani Perica"
description:	       "Apartments in Sukošan"

# i18n
languages: ["en", "cs", "de", "nl", "fr", "hu", "hr"]
exclude_from_localizations: ["javascript", "images", "css"]

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
